### ISSUE TITLE
Add OSS license

### ISSUE THREAD

**Issue by Dynnammo** [tournesol-app/tournesol-backend#23]
As the software is going to grow up and aims to gather multiple developers, it would be a good idea to license Tournesol under a juridiction that suits its purpose (AGPLv3, GNU GPL, etc.)

- [x] Add license.txt file to `tournesol-backend` and `tournesol-frontend`

**Comment by lfaucon** [comment]
Yes, indeed. We had a license on our former repository (https://github.com/tournesol-app/tournesol/blob/master/LICENSE) but decided to rewrite the codebase from scratch. We should indeed add the license again. Thanks for raising this point!

Do you think that MIT is not the right license for Tournesol? Why or why not?

**Comment by Dynnammo** [comment]
To be straightforward I'm not an expert on that subject, MIT could do the job. I'm currently working on [that project](github.com/decidim/decidim) on which they choose to use AGPLv3 to force any participants to make public the modification they made (AGPLv3 = MIT + restraining the liberty of keeping your modifications private). 
Back to the case of tournesol, it would prevent companies to take the project and modify it internally without giving these modifications back to the community.

**Comment by GresilleSiffle** [comment]
Hello : ]

For me, the GNU General Public License is a very good license for Tournesol.

Contrary to `MIT`, `Zero-Clause BSD` and other licenses that are very closed to the « public domain », the GNU GPL comes with a philosophy and a strong copyleft that provides two things:
- liberty (to run, read, study, modify, distribute the program, etc.) ;
- and a protection for this liberty.

The second point is the main difference between what we can call Libre Softwares and other Open Source Softwares. It's precisely this point that makes a software a Libre Software (or Free Software). I perfer using the word Libre to avoid confusion with Free as in free beer : )

If the back end project contains code, let's say a machine learning algorithm, able to impact people judgment, or behaviour, or  the any aspect of a given society: making the code available with a open license is a good act of transparency and honesty. That what most of the Open Source licenses do. Moreover preventing this code from being closed and used with opacity protects people from being manipulated or even betrayed. That what GNU GPL is made for.

Also, note that Tournesol can uses different licenses for all of its components. The documentation can distributed under the term of Creative Commons, or a more text oriented license so that everyone can share it easily. The AI algorithms could be GNU GPLv3, the rest of the back end could another license without a strong copyleft, etc. To keep things simple, I recommend using different licenses only for documentation, source code, and media like images, and video if relevant.

Choosing a license is an important step for an open project, let's discuss more : ]

I found several articles on the GNU Project very instructing:

- What is a free software? https://www.gnu.org/philosophy/free-sw.en.html
- Free Software Is Even More Important Now https://www.gnu.org/philosophy/free-software-even-more-important.en.html
- Why programs must not limit the freedom to run them? https://www.gnu.org/philosophy/programs-must-not-limit-freedom-to-run.en.html
- Licenses and comments https://www.gnu.org/licenses/license-list.en.html

Bonus:
- A matrix of licenses https://choosealicense.com/appendix/

**Comment by lenhoanglnh** [comment]
Maybe we can have a different license for the code and the public database?

- I fully agree with having the documentation in Creative Commons.
- I also agree with Libre Software (GNU GPL) for the source code, especially the ML code.
- On the other hand, I would like any company to re-use the Tournesol public database, and I understand that, in the current legal and economic context, they might not want to publicly share the code they use to leverage the Tournesol public database.  (I'm more hesitant about this last point)

(of course, ideally, a law would force them to have such a code audited at least by third parties like academics... and they would be strongly incentivized to make at least part of it publicly available...)

**Comment by GresilleSiffle** [comment]
> Maybe we can have a different license for the code and the public database?

Of course, we can always distribute the database under the term of a more appropriate license for data.

I don't know weel those kinds of license, fortunately Wikipedia is a good starting point : )

https://fr.wikipedia.org/wiki/Donn%C3%A9es_ouvertes#Licences_open_data

I linked the french page because the english version contains too few information about licenses.

**Comment by lfaucon** [comment]
Done! Thanks @Dynnammo for bringing this up. Let us know if you see additional issues
